### ISSUE TITLE
error on whoops (car+solar)

### ISSUE THREAD

**Issue by frostymccool** [mcolyer/tesla-solar-fetcher#1]
Matt, this looks great, would like to help test / get working for systems with car also.
Note from your readme that it would be relatively easy, but can't test. I can try / test if you like?
currently when I run I get the following back: (I instrumented to show the body)
whoops: json: cannot unmarshal number into Go struct field Product.response.id of type string
body: [123 34 114 101 115 112 111 110 115 101 34 58 110 117 108 108 44 34 101 114 114 111 114 34 58 34 110 111 116 95 102 111 117 110 100 34 44 34 101 114 114 111 114 95 100 101 115 99 114 105 112 116 105 111 110 34 58 34 34 125]

I have a model 3 and solar as the 2 instances in my app.
Ian.

[update]
looks like it's further up - I get a 404 from the Get

> get: &{GET https://owner-api.teslamotors.com/api/1/energy_sites/0/history?kind=power&date=2020-08-13T00:00:00.000Z&period=_day&time_zone=America/Los_Angeles HTTP/1.1 1 1 map[] <nil> <nil> 0 [] false owner-api.teslamotors.com map[] map[] <nil> map[]   <nil> <nil> <nil> 0x14140a8}
> resp: &{404 Not Found 404 HTTP/2.0 2 0 map.....

**Comment by frostymccool** [comment]
I see what you mean about easy fix now/hack.. changed to select product 1 instead of 0
`		return parsed.Products[1].EnergySiteId, nil
`
it now works... for ref, my site parsed does have the format pushing solar from 0 to 1

> siteParsed: &{2 [{ 0  0 false false} {353abf43-xxxx-xxxx-xxxx-xxxxxxxxxxxx xxxxxxx solar 0 false false}]}

**Comment by mcolyer** [comment]
Glad you were able to get it worked out - also open to accepting a PR if
you want to make it more generalized.
